### 1. Creating Arrays from Existing Data


* numpy.array(object, dtype=None)



* Creates an array from a list, tuple, or another array.



In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


* numpy.asarray(a, dtype=None)



* Similar to np.array, but does not copy the array if it is already a NumPy array.



In [3]:
lst = [1, 2, 3]
arr = np.asarray(lst)
print(arr)

[1 2 3]


* numpy.copy(a)


* Returns a new copy of the array.



In [21]:
arr = np.array([1, 2, 3])
new_arr = np.copy(arr)
print(new_arr)


[1 2 3]


### 2. Creating Arrays with Placeholders (Zeros, Ones, Empty)


* numpy.zeros(shape, dtype=float)



* Creates an array filled with zeros.



In [22]:
arr = np.zeros((2, 3))
print(arr)  # 2x3 matrix of zeros

[[0. 0. 0.]
 [0. 0. 0.]]


* numpy.ones(shape, dtype=float)



* Creates an array filled with ones.



In [24]:
arr = np.ones((3, 3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


* numpy.full(shape, fill_value, dtype=None)



* Creates an array filled with a specified value.



In [23]:
arr = np.full((2, 2), 7) 
print(arr) # 2x2 array filled with 7


[[7 7]
 [7 7]]


* numpy.empty(shape, dtype=float)



* Creates an uninitialized array (values may be random).



In [25]:
arr = np.empty((2, 2))
print(arr)


[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 9.97373574e-312]]


### 3. Creating Identity and Diagonal Matrices


* numpy.eye(N, M=None, k=0, dtype=float)



* Creates an identity matrix or a diagonal matrix.



In [26]:
arr = np.eye(3)
print(arr)  # 3x3 identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* numpy.identity(n, dtype=float)



* Creates an identity matrix of size n x n.



In [27]:
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


* numpy.diag(v, k=0)



* Creates a diagonal matrix from a given array.



In [28]:
arr = np.diag([1, 2, 3])
print(arr)  # Diagonal matrix with 1, 2, 3


[[1 0 0]
 [0 2 0]
 [0 0 3]]


### 4. Creating Arrays with Ranges and Intervals


* numpy.arange(start, stop, step, dtype=None)



* Creates an array with evenly spaced values (similar to Python’s range).



In [29]:
arr = np.arange(1, 10, 2)
print(arr)  # [1, 3, 5, 7, 9]


[1 3 5 7 9]


* numpy.linspace(start, stop, num=50, endpoint=True, dtype=None)



* Creates an array with num evenly spaced values between start and stop.



In [30]:
arr = np.linspace(0, 10, 5)
print(arr)  # [0, 2.5, 5, 7.5, 10]


[ 0.   2.5  5.   7.5 10. ]


* numpy.logspace(start, stop, num=50, base=10.0, dtype=None)



* Similar to linspace, but spaced logarithmically.



### 5. Creating Randomized Arrays


* numpy.random.rand(d0, d1, ..., dn)



* Creates an array of shape (d0, d1, ..., dn) with random values in the range [0, 1).



In [40]:
arr = np.random.rand(3, 3)
print(arr)

[[0.15008673 0.4561153  0.71387413]
 [0.14886419 0.05736694 0.95524201]
 [0.92049747 0.44275532 0.29797087]]


* numpy.random.randint(low, high, size, dtype=int)



* Generates an array of random integers.



In [42]:
arr = np.random.randint(1, 10, (3, 3))
print(arr)

[[4 8 5]
 [7 1 2]
 [4 2 5]]


* numpy.random.randn(d0, d1, ..., dn)



* Returns a sample from the standard normal distribution.



In [43]:
arr = np.random.randn(3, 3)
print(arr)

[[ 0.89093489  1.5132599   0.30929306]
 [-0.42732606  0.33107747 -1.30287931]
 [-1.09536741 -0.7005786  -0.19271918]]


* numpy.random.choice(a, size, replace=True, p=None)



* Generates a random sample from a given 1D array.



In [47]:
arr = np.random.choice([10, 20, 30], size=(2,5))
print(arr)

[[10 30 30 10 10]
 [20 30 20 20 20]]


### 6. Creating Structured Arrays


* numpy.meshgrid(x, y, indexing='xy')



* Creates coordinate matrices from coordinate vectors.



In [37]:
x = np.array([0, 1, 2])
y = np.array([0, 1])
xx, yy = np.meshgrid(x, y)
print(xx, yy)

[[0 1 2]
 [0 1 2]] [[0 0 0]
 [1 1 1]]


* numpy.indices(dimensions, dtype=int)



* Returns an array of indices.



In [38]:
arr = np.indices((3, 3))
print(arr)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


* numpy.mgrid and numpy.ogrid



* Create mesh grids using slices.



In [51]:
arr = np.mgrid[1:5, 1:5]
print(arr)

[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]
  [4 4 4 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
