### 1. Creating Arrays from Python Lists or Tuples


##### numpy.array(object, dtype=None)


* Converts a Python list, tuple, or another array-like object into a NumPy array.



In [2]:
import numpy as np

# From list
arr1 = np.array([1, 2, 3, 4])
print(arr1)

# From tuple
arr2 = np.array((5, 6, 7, 8))
print(arr2)


[1 2 3 4]
[5 6 7 8]


* Multidimensional Example:

In [3]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)


[[1 2 3]
 [4 5 6]]


### 2. Using numpy.asarray()


##### numpy.asarray(a, dtype=None, order=None)


* Converts an input to an array but does not copy if it's already an array (more efficient than np.array).



In [4]:
lst = [1, 2, 3]
arr = np.asarray(lst)
print(arr)


[1 2 3]


* With dtype specification:

In [5]:
arr = np.asarray(lst, dtype=float)
print(arr)  

[1. 2. 3.]


* With an existing NumPy array (no copy operation):

In [6]:
arr = np.array([1, 2, 3])
arr2 = np.asarray(arr)  
print(arr2)

[1 2 3]


### 3. Creating Arrays from Buffers


##### numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)


* Creates a NumPy array from a binary buffer.


In [7]:
s = b'Hello World'
arr = np.frombuffer(s, dtype='S1')  # Create an array of single characters
print(arr)  # [b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


### 4. Creating Arrays from Iterators


##### numpy.fromiter(iterable, dtype, count=-1)


* Converts an iterable (like a generator) into a NumPy array.



In [12]:
iterable = (x * x for x in range(5))  # Generator
arr = np.fromiter(iterable, dtype=int)
print(arr)  

[ 0  1  4  9 16]


### 5. Creating Arrays from String Data


##### numpy.fromstring(string, dtype=float, count=-1, sep=' ')


* Creates an array from a string of numbers.



In [17]:
s = "1,2,3,4,5"
arr = np.fromstring(s, dtype=int, sep=',')
print(arr) 

[1 2 3 4 5]
