### 1. Creating Arrays with a Range of Values


##### numpy.arange(start, stop, step)


* Similar to Python's range(), but returns a NumPy array.



In [ ]:
import numpy as np

arr = np.arange(1, 10, 2) 
print(arr)  


[1 3 5 7 9]


* With floating-point values:


In [2]:
arr = np.arange(0, 5, 0.5)
print(arr) 


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


### 2. Creating Arrays with Evenly Spaced Values


##### numpy.linspace(start, stop, num=50, endpoint=True, dtype=None)


* Generates num evenly spaced values between start and stop.



In [3]:
arr = np.linspace(0, 10, 5)  
print(arr)  

[ 0.   2.5  5.   7.5 10. ]


* Excluding the endpoint:

In [4]:
arr = np.linspace(0, 10, 5, endpoint=False)
print(arr) 


[0. 2. 4. 6. 8.]


### 3. Creating Arrays with Logarithmically Spaced Values


##### numpy.logspace(start, stop, num=50, base=10.0, dtype=None)


* Similar to linspace, but values are spaced logarithmically.



* start and stop refer to exponents of base.



In [5]:
arr = np.logspace(1, 3, 4) 
print(arr)

[  10.           46.41588834  215.443469   1000.        ]


* With a different base:

In [6]:
arr = np.logspace(2, 4, 5, base=2) 
print(arr) 


[ 4.          5.65685425  8.         11.3137085  16.        ]
