In [2]:
import numpy as np

# 1. What is Indexing in Array NumPy?
 Indexing in NumPy means selecting specific elements from an array


 It allows us to access and modify elements based on their position (index).

# *. 1D Array indexing 

In [16]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[4])  # First element (10)
print(arr[2])  # Third element (30)
print(arr[-1])  # Last element (50)

50
30
50


# *.  2D Array Indexing (Rows & Columns)
A 2D array is like a table (rows and columns).


We use two indexes: arr[row_index, column_index].

In [17]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print(arr_2d)
print(arr_2d[0, 1])  # First row, second column (2)
# print(arr_2d[2, -1])  # Last row, last column (9)


2


# *. Indexing in 3D Arrays
arr[depth, row, column]


In [5]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                    [[7, 8, 9], [10, 11, 12]]])

print(arr_3d[0, 1, 2])  # First 2D array, second row, third column (6)
print(arr_3d[1, 0, -1]) # Second 2D array, first row, last column (9)



6
9


# 6. Modifying Elements Using Indexing
Indexing allows us to change values in an array.



# Modifying a Single Element

In [6]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 99  # Change the third element (index 2)
print(arr)  # [1, 2, 99, 4, 5]


[ 1  2 99  4  5]


# Modifying Multiple Elements

In [7]:
arr = np.array([1, 2, 3, 4, 5])
arr[[0, 3]] = [100, 400]  # Modify elements at index 0 and 3
print(arr)  # [100, 2, 99, 400, 5]


[100   2   3 400   5]


In [8]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr_2d[1, :])  # Entire second row → [5, 6, 7, 8]
print(arr_2d[:, 2])  # Entire third column → [3, 7, 11]


[5 6 7 8]
[ 3  7 11]


# 7. Reversing an Array Using Indexing


Reversing a 1D Array


In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1]) 


[5 4 3 2 1]


Reversing Rows or Columns in 2D Arrays


In [21]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d.ndim)
print(arr_2d)

# print(arr_2d[::-1])  # Reverse rows
# 
# print(arr_2d[:, ::-1])  # Reverse columns
# 
print(arr_2d[::-1, ::-1])  # Reverse both rows and columns



2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
import numpy as np

arr_3d = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9],[10,11,12]]])
print(arr_3d.ndim)
print(arr_3d)

# print(arr_3d[:, ::-1, :]) # Reverse rows


# print(arr_3d[:, :, ::-1])  # Reverse columns



print(arr_3d[::-1,::-1,::-1])  # Reverse both  rows columns 


3
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[[ 3  2  1]
  [ 6  5  4]
  [ 9  8  7]
  [12 11 10]]]


# Slicing 

Slicing in NumPy allows you to extract specific elements from an array using:

1️⃣ Slicing in 1D Arrays

In [12]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])   # [20 30 40] → Elements from index 1 to 3
print(arr[:3])    # [10 20 30] → First three elements
print(arr[2:])    # [30 40 50 60] → From index 2 to end
print(arr[::-1])  # [60 50 40 30 20 10] → Reversed array


[20 30 40]
[10 20 30]
[30 40 50 60]
[60 50 40 30 20 10]


2️⃣ Slicing in 2D Arrays


In [13]:
arr_2d = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])

print(arr_2d[1:, 2:])   # [[7 8] [11 12]] → Rows 1 to end, columns 2 to end
print(arr_2d[:, 1])     # [2 6 10] → All rows, second column
print(arr_2d[::-1, ::-1])  # Reverse rows & columns


[[ 7  8]
 [11 12]]
[ 2  6 10]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


3️⃣ Slicing in 3D Arrays

In [14]:
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
])

print(arr_3d[:, :, 1])   # Select second column from all depth slices
print(arr_3d[::-1, ::-1, ::-1])  # Reverse depth, rows, and columns


[[ 2  5]
 [ 8 11]]
[[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]


In [15]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10,11,12]],[[21, 22, 23], [24, 25, 26]],[[27, 28, 29],[30,1,12]]])
# print(arr_3d)

print(arr_3d[::-1,::-1])


[[[30  1 12]
  [27 28 29]]

 [[24 25 26]
  [21 22 23]]

 [[10 11 12]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 1  2  3]]]
