In [ ]:
import numpy as np

# 1. What is Indexing in Array NumPy?
 Indexing in NumPy means selecting specific elements from an array


 It allows us to access and modify elements based on their position (index).

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # First element (10)
print(arr[2])  # Third element (30)
print(arr[-1])  # Last element (50)

# 2.  2D Array Indexing (Rows & Columns)
A 2D array is like a table (rows and columns).


We use two indexes: arr[row_index, column_index].

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d[0, 1])  # First row, second column (2)
print(arr_2d[2, -1])  # Last row, last column (9)


# 3. Indexing in 3D Arrays
arr[depth, row, column]


In [15]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                    [[7, 8, 9], [10, 11, 12]]])

print(arr_3d[0, 1, 2])  # First 2D array, second row, third column (6)
print(arr_3d[1, 0, -1]) # Second 2D array, first row, last column (9)



6
9


# 4. Boolean Indexing (Filtering Elements)


We can filter elements using conditions.



In [16]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])  # Output: [30, 40, 50]


[30 40 50]


# 5. Selecting Multiple Elements


We can select multiple elements using a list of indexes.



In [203]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4] ]) 


[10 30 50]


# 6. Modifying Elements Using Indexing
Indexing allows us to change values in an array.



# Modifying a Single Element

In [18]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 99  # Change the third element (index 2)
print(arr)  # [1, 2, 99, 4, 5]


[ 1  2 99  4  5]


# Modifying Multiple Elements

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[[0, 3]] = [100, 400]  # Modify elements at index 0 and 3
print(arr)  # [100, 2, 99, 400, 5]


[100   2   3 400   5]


# 7. Extracting Rows and Columns from a 2D Array

In [20]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])

print(arr_2d[1, :])  # Entire second row → [5, 6, 7, 8]
print(arr_2d[:, 2])  # Entire third column → [3, 7, 11]


[5 6 7 8]
[ 3  7 11]


# 8. Reversing an Array Using Indexing


Reversing a 1D Array


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1]) 


[5 4 3 2 1]


Reversing Rows or Columns in 2D Arrays


In [59]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d.ndim)

print(arr_2d[::-1])  # Reverse rows

print(arr_2d[:, ::-1])  # Reverse columns

print(arr_2d[::-1, ::-1])  # Reverse both rows and columns



2
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [200]:
import numpy as np

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10,11,12]]])
print(arr_3d.ndim)
# print(arr_3d)
print(arr_3d[::-1,::-1])

# print(arr_3d[:, ::-1, :]) # Reverse rows


# print(arr_3d[:, :, ::-1])  # Reverse columns


# print(arr_3d[::-1,::-1,::-1])  # Reverse both  rows columns 


3
[[[10 11 12]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 1  2  3]]]


In [195]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10,11,12]],[[21, 22, 23], [24, 25, 26]],[[27, 28, 29],[30,31,32]]])
# print(arr_3d)

print(arr_3d[::-1,::-1])


[[[30 31 32]
  [27 28 29]]

 [[24 25 26]
  [21 22 23]]

 [[10 11 12]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 1  2  3]]]
