### 1. Integer Array Indexing (Fancy Indexing)

Instead of slicing, you can use arrays of indices to access specific elements.

##### 1D Example:

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]  # Select elements at positions 0, 2, and 4
print(arr[indices]) 


[10 30 50]


##### 2D Example:

####
|        | Column 1| Column 2| Column 3|
|--------|---------|---------|---------|
| Row 1  |   10    |   20    |   30    |
| Row 2  |   40    |   50    |   60    |
| Row 3  |   70    |   80    |   90    |
 

In [2]:
arr2D = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])

rows = [0, 1]   # First and second rows
cols = [1, 2]   # Second and third columns
print(arr2D[rows, cols])  


[20 60]


* Selecting entire rows or columns:

####
|        | Column 1| Column 2| Column 3|
|--------|---------|---------|---------|
| Row 1  |   10    |   20    |   30    |
| Row 2  |   40    |   50    |   60    |
| Row 3  |   70    |   80    |   90    |
 

In [3]:
print(arr2D[[0, 2], :])  # Select rows 0 and 2
print()
print(arr2D[:, [1, 2]])  # Select columns 1 and 2


[[10 20 30]
 [70 80 90]]

[[20 30]
 [50 60]
 [80 90]]


##### 2. Boolean Indexing

Boolean indexing allows selecting elements based on conditions.



##### 1D Example:

In [4]:
arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25  # Create a boolean mask
print(arr[mask]) 


[30 40 50]


##### 2D Example:

In [7]:
arr2D = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])

mask = arr2D % 20 == 0  # Find elements divisible by 40
print(arr2D[mask]) 


[20 40 60 80]


* Using multiple conditions:

In [ ]:
print(arr[(arr > 20) & (arr < 50)])  


[30 40]


### 3. np.where() for Conditional Selection


numpy.where(condition, x, y) returns indices where condition is True, or replaces values based on a condition.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.where(arr > 25)
print(indices)  # Output:  (positions where arr > 25)
print(arr[indices]) 


(array([2, 3, 4], dtype=int64),)
[30 40 50]


* Replacing values based on conditions:

In [ ]:
print(np.where(arr > 25, 100, 0))  
# Output: [  0   0 100 100 100] (Replaces values > 25 with 100, others with 0)


[  0   0 100 100 100]


### 4. np.take() for Advanced Indexing

np.take() retrieves elements along a specified axis.

### np.where(condition, value_if_true, value_if_false)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(np.take(arr, [0, 2, 4]))  


[10 30 50]


##### 2D Example:

In [ ]:
arr2D = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])

print(np.take(arr2D, [0, 4, 8]))  


[10 50 90]


### 5. np.choose() for Multi-Index Selection


np.choose() selects elements from multiple arrays based on an index array.



In [ ]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])
arr3 = np.array([70, 80, 90])

choice = np.array([0, 1, 2])  # Select arr1[0], arr2[1], arr3[2]
print(np.choose(choice, [arr1, arr2, arr3]))  

[10 50 90]
