### 1. Rules for Broadcasting

When performing operations on arrays of different shapes, NumPy follows these rules:



1. Match dimensions from right to left

* If dimensions are equal → No change needed

* If one dimension is 1 → It gets expanded to match the other dimension

* If dimensions are different and neither is 1 → Broadcasting fails (throws an error)

2.Expand singleton dimensions (1)

* A shape (1, n) can behave like (m, n) if needed.

### 2. Examples of Broadcasting

#### Example 1: Adding a Scalar to an Array

A scalar (single value) is broadcasted across the entire array.

In [11]:
import numpy as np

arr = np.array([1, 2, 3])
scalar = 10

result = arr + scalar  # Broadcasting
print(result)  # Output: [11 12 13]


[11 12 13]


##### How it works?

* The scalar 10 is expanded to [10, 10, 10] to match the array shape.

### Example 2: Broadcasting a 1D Array to a 2D Array

In [12]:
A = np.array([[1], [2], [3]])  # Shape (3,1)
B = np.array([10, 20, 30])     # Shape (1,3)

result = A + B  # Broadcasting
print(result)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


#### How it works?

* A has shape (3,1), which expands to (3,3).

* B has shape (1,3), which expands to (3,3).

* Addition is performed element-wise.

### Example 3: Broadcasting in 3D

In [20]:
X = np.ones((3, 1, 4))  # Shape (3,1,4)
Y = np.array([1, 2, 3, 4])  # Shape (4,) → (1,1,4)
result = X + Y
print(result.shape)  # Output: (3,1,4)


(3, 1, 4)


* Y is reshaped to (1,1,4), then broadcasted across (3,1,4).

### 3. When Broadcasting Fails


If two arrays have incompatible shapes that cannot be expanded, NumPy raises an error.


In [29]:
B = np.array([[1, 2], [3, 4]]) 
A = np.array([[1, 2, 3],[1, 2, 3]])  

# This will raise an error
B+A


ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

❌ Error: operands could not be broadcast together with shapes (3,) (2,2)

Why?

* (3,) and (2,2) cannot be aligned for broadcasting.

### 4. Broadcasting Best Practices

✅ Use np.newaxis or reshape() to adjust array dimensions manually if needed.

In [15]:
A = np.array([1, 2, 3])[:, np.newaxis]  # Shape (3,1)
B = np.array([10, 20])  # Shape (2,)

result = A + B  # Now possible
print(result.shape)  # Output: (3,2)


(3, 2)
