# NumPy Iterating Over Arrays

This notebook demonstrates various ways to iterate over NumPy arrays, including:
- Iterating over 1D arrays
- Iterating over 2D arrays (rows and elements)
- Iterating over 3D arrays
- Using `nditer()` for efficient iteration
- Iterating with different data types using `op_dtypes`
- Using `ndenumerate()` to track indices while iterating

In [1]:
import numpy as np  # Importing NumPy
print("NumPy imported successfully!")

NumPy imported successfully!


## 1. Iterating Over 1D Arrays

Iterate through each element of a 1D array using a simple `for` loop.

In [2]:
arr = np.array([1, 2, 3, 4, 5])
for element in arr:
    print(element)

1
2
3
4
5


## 2. Iterating Over 2D Arrays (Rows and Elements)

For a 2D array, iterating over elements will return rows one by one.

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr:
    print(row)  # Printing each row


[1 2 3]
[4 5 6]


To iterate over individual elements, use a nested loop.

In [4]:
for row in arr:
    for element in row:
        print(element)

1
2
3
4
5
6


## 3. Iterating Over 3D Arrays

For a 3D array, iterating returns 2D sub-arrays.

In [5]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Iterating over 2D matrices
for matrix in arr:
    print(matrix)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


To iterate over individual elements in a 3D array, use nested loops.

In [6]:
for matrix in arr:
    for row in matrix:
        for element in row:
            print(element)

1
2
3
4
5
6
7
8


## 4. Using `nditer()` for Efficient Iteration

The `nditer()` function allows efficient iteration over all elements of an array.

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for element in np.nditer(arr):
    print(element)

1
2
3
4
5
6


## 5. Iterating With Different Data Types (`op_dtypes`)

We can specify the output data type while iterating.

In [8]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['float']):
    print(x)

1.0
2.0
3.0


## 6. Iterating With `ndenumerate()`

To track indices while iterating, use `ndenumerate()`.

In [9]:
arr = np.array([[10, 20], [30, 40]])
for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


## Summary Table

| Method                | Use Case |
|----------------------|----------------------------|
| Simple `for` loop | Best for 1D arrays |
| Nested `for` loops | For iterating over elements in 2D+ arrays |
| `nditer()` | Efficient iteration over all elements |
| `ndenumerate()` | Iterates while tracking indices |

This concludes our guide on iterating over NumPy arrays! 🚀