# NumPy Array Manipulation

This notebook covers various NumPy array manipulation techniques.

In [1]:
import numpy as np

## Creating and Reshaping Arrays

Reshaping changes the structure of the array without modifying data.

In [2]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Flattening Arrays

Flattening converts a multi-dimensional array into a one-dimensional array.

In [3]:
flattened = reshaped.flatten()
print("Flattened Array:", flattened)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## Transposing Arrays

Transposing swaps rows and columns.

In [4]:
transposed = reshaped.T
print("Transposed Array:\n", transposed)

Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Stacking Arrays

Stacking allows combining multiple arrays horizontally or vertically.

In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

h_stacked = np.hstack((a, b))
print("Horizontally Stacked:\n", h_stacked)

v_stacked = np.vstack((a, b))
print("Vertically Stacked:\n", v_stacked)

Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]
Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Splitting Arrays

Splitting divides an array into multiple sub-arrays.

In [6]:
split_h = np.hsplit(h_stacked, 2)
print("Horizontal Split:", split_h)

split_v = np.vsplit(v_stacked, 2)
print("Vertical Split:", split_v)

Horizontal Split: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
Vertical Split: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


## Adding & Removing Elements

Elements can be inserted or removed dynamically.

In [7]:
arr = np.array([1, 2, 3, 4])
new_arr = np.insert(arr, 2, 99)
print("Array after insertion:", new_arr)

removed_arr = np.delete(arr, 1)
print("Array after deletion:", removed_arr)

Array after insertion: [ 1  2 99  3  4]
Array after deletion: [1 3 4]
